AND-2919 tangem integration android
tangem/wallet-core pull request #2
Opened 2023-03-13 07:29 UTC by Yoggam1

## Description

## How to test

## Types of changes

## Checklist

- [ ] Create pull request as draft initially, unless its complete.
- [ ] Add tests to cover changes as needed.
- [ ] Update documentation as needed.
- [ ] If there is a related Issue, mention it in the description.

If you're adding a new blockchain

- [ ] I have read the [guidelines](https://developer.trustwallet.com/wallet-core/newblockchain#integration-criteria) for adding a new blockchain.

2023-03-13 08:01 UTC, iiiburnyiii commented on jni/java/wallet/core/java/TangemSigner.java
> +        outputData = null;
Это нужно?

2023-03-13 08:09 UTC, megakoko commented
Добавь пожалуйста везде комментарий `TANGEM` у нашего нового кода. В скриптах где нет явной области видимости — давай сделаем такой коммент в начале и конце.

2023-03-13 08:47 UTC, megakoko requested changes

2023-03-13 08:47 UTC, megakoko commented on android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/tron/TestTronTransactionSigner.kt
> -import org.junit.Assert.assertArrayEquals
Никаких удалений не должно быть. Только добавления. Если добавляешь что-то — добавляй отдельно от кода трастволлета. В данном случае — после всех импортов.

2023-03-13 08:47 UTC, megakoko commented on android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/tron/TestTronTransactionSigner.kt
> +            .setAmount(ByteString.copyFrom("0x00000000000000000000000000000000000000000000000000000000000003e8".toHexByteArray()))
Давай в стандартном методе сделаем этот тест, без копипасты всех параметров.

2023-03-13 08:47 UTC, megakoko commented on android/build.gradle
> +        classpath 'com.android.tools.build:gradle:7.0.0'
Оставить 4.2.2 нельзя?

2023-03-13 08:47 UTC, megakoko commented on android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip
Нельзя оставить 6.9.2?

2023-03-13 08:47 UTC, megakoko commented on include/TrustWalletCore/TWAnySignerTangem.h
> +extern TWData *_Nonnull TWAnySignerSignExternallyAndroid(TWData* _Nonnull input, enum TWCoinType coin, TWData *_Nonnull publicKey, std::function<const TWData *_Nonnull(const TWData *_Nonnull)> extern
Нужен перевод строки в конце файла. И в других файлах.

<img width="93" alt="Screenshot 2023-03-13 at 11 17 23" src="https://user-images.githubusercontent.com/12209839/224644488-fd9ecf96-73de-4392-8e4a-3afd2f68aa96.png">

2023-03-13 08:47 UTC, megakoko commented on include/TrustWalletCore/TWAnySignerTangem.h
> +extern TWData *_Nonnull TWAnySignerSignExternallyAndroid(TWData* _Nonnull input, enum TWCoinType coin, TWData *_Nonnull publicKey, std::function<const TWData *_Nonnull(const TWData *_Nonnull)> extern
В начало файла надо добавить `#pragma once`

2023-03-13 08:47 UTC, megakoko commented on tools/android-test
> +./gradlew assembleAndroidTest --info
Надо убрать

2023-03-13 08:47 UTC, megakoko commented on tools/android-build
> +./gradlew assembleRelease --info
Надо убрать

2023-03-13 08:47 UTC, megakoko commented on jni/cpp/TangemSigner.h
> +#endif // JNI_TW_TANGEMSIGNER_H
#ifdef #define #endif надо заменить на `#pragma once` в начале файла

2023-03-13 08:47 UTC, megakoko commented on jni/cpp/TangemSigner.cpp
> +static JavaVM* cachedJVM;
Давай добавим инициализацию nullptr

2023-03-13 08:47 UTC, megakoko commented on jni/cpp/TangemSigner.cpp
> +#include <TrustWalletCore/TWAnySignerTangem.h>
Все эти инклуды нужны?

2023-03-13 08:47 UTC, megakoko commented on jni/cpp/TangemSigner.cpp
> +TWData *_Nonnull callbackFunc(jobject signer, TWData *_Nonnull data) {
Нужно нормальное название.

2023-03-13 08:47 UTC, megakoko commented on src/interface/TWAnySigner.cpp
> +
Тут получится переписать одну функцию через другую?

2023-03-13 08:47 UTC, megakoko commented on jni/cpp/TangemSigner.cpp
> +    JNIEnv *env;
Все указатели надо инициализировать через nullptr если это C++ или NULL если это C.

2023-03-13 08:47 UTC, megakoko commented on jni/cpp/TangemSigner.cpp
> +    cachedJVM -> AttachCurrentThread(&env, NULL);
Лишние пробелы при разыменовании указателя надо везде убрать

2023-03-13 08:47 UTC, megakoko commented on jni/cpp/TangemSigner.cpp
> +    jbyteArray aret = (jbyteArray) env -> CallObjectMethod(signer, signMethodId, a);
Нужны нормальные названия. 

a
cls
aret
ret

2023-03-13 08:47 UTC, megakoko commented on jni/cpp/TangemSigner.cpp
> +    std::function<const TWData *_Nonnull(const TWData *_Nonnull)> externalSigner = std::bind(callbackFunc, globalSigner, std::placeholders::_1);
Тут на auto можно тип заменить?

2023-03-13 08:47 UTC, megakoko commented on jni/java/wallet/core/java/TangemSigner.java
> +        byte[] data = input.toByteArray();
inputData

2023-03-13 08:47 UTC, megakoko commented on jni/cpp/TangemSigner.cpp
> +    env -> GetJavaVM(&cachedJVM);
Давай в конце метода обнулять cachedJVM

2023-03-13 08:48 UTC, megakoko commented
Ты пробовал Signer с асинхронным методом sign? С обычной задержкой например

2023-03-13 09:48 UTC, gbixahue commented
Название ветки не содержит названия задачи

2023-03-14 08:20 UTC, Yoggam1 commented on android/build.gradle
> +        classpath 'com.android.tools.build:gradle:7.0.0'
> Оставить 4.2.2 нельзя?
Unfortunately not. But it will affect only local builds for android. @megakoko

2023-03-14 08:41 UTC, Yoggam1 commented on jni/java/wallet/core/java/TangemSigner.java
> +        outputData = null;
Yes

2023-03-14 12:31 UTC, Yoggam1 commented on android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip
нельзя поднять на 8.0.2(ломается билд) и оставить 6.9.2(не будет билдиться проект)

2023-03-14 12:32 UTC, Yoggam1 commented on android/build.gradle
> +        classpath 'com.android.tools.build:gradle:7.0.0'
Не получиться поднять на 7.4.2 там ломается билд и я пока не нашел быстрого решения для исправления

2023-03-14 12:51 UTC, Yoggam1 commented on tools/android-test
> +./gradlew assembleAndroidTest --info
Почему?

2023-03-14 12:51 UTC, Yoggam1 commented on tools/android-build
> +./gradlew assembleRelease --info
Почему?

2023-03-14 13:03 UTC, Yoggam1 commented on jni/cpp/TangemSigner.h
> +#endif // JNI_TW_TANGEMSIGNER_H
Это было скопиравано из аналогичного библиотечного файла, который на уровне JNI. Поэтому мне кажется лучше так оставить это

2023-03-15 08:13 UTC, megakoko commented on android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip
А как в трастволлете собирают с 6.9.2?

2023-03-15 08:25 UTC, megakoko commented on android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/tron/TestTronTransactionSigner.kt
> +        )
Надо оставить стантардный тест в дополнении к нашему. И надо делать через AnySigner, не через TangemSigner напрямую.

2023-03-15 08:25 UTC, megakoko commented on tools/android-test
> +./gradlew assembleAndroidTest --info
Чем меньше изменений в проекте — тем лучше

2023-03-15 08:25 UTC, megakoko commented on jni/cpp/TangemSigner.h
> +#endif // JNI_TW_TANGEMSIGNER_H
Это анахронизм

2023-03-15 08:25 UTC, megakoko commented on jni/cpp/TangemSigner.cpp
> +#include <TrustWalletCore/TWAnySignerTangem.h>
Где в этом файле используются stdio, std::vector, std::string?

2023-03-15 12:09 UTC, Yoggam1 commented on jni/cpp/TangemSigner.cpp
> +    env -> GetJavaVM(&cachedJVM);
+

2023-03-15 12:11 UTC, Yoggam1 commented on android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/tron/TestTronTransactionSigner.kt
> -import org.junit.Assert.assertArrayEquals
✅

2023-03-15 12:12 UTC, Yoggam1 commented on jni/cpp/TangemSigner.cpp
> +#include <TrustWalletCore/TWAnySignerTangem.h>
✅

2023-03-15 12:12 UTC, Yoggam1 commented on src/interface/TWAnySigner.cpp
> +
✅

2023-03-15 12:12 UTC, Yoggam1 commented on jni/cpp/TangemSigner.cpp
> +    JNIEnv *env;
✅

2023-03-15 12:12 UTC, Yoggam1 commented on jni/cpp/TangemSigner.cpp
> +    cachedJVM -> AttachCurrentThread(&env, NULL);
✅

2023-03-15 12:12 UTC, Yoggam1 commented on jni/cpp/TangemSigner.cpp
> +    jbyteArray aret = (jbyteArray) env -> CallObjectMethod(signer, signMethodId, a);
✅

2023-03-15 12:12 UTC, Yoggam1 commented on jni/cpp/TangemSigner.cpp
> +    std::function<const TWData *_Nonnull(const TWData *_Nonnull)> externalSigner = std::bind(callbackFunc, globalSigner, std::placeholders::_1);
✅

2023-03-15 12:21 UTC, megakoko commented on jni/java/wallet/core/java/TangemSigner.java
> +        byte[] data = input.toByteArray();
Я имел в виду название переменной. MessageLite это input, байты это inputData

2023-03-15 12:44 UTC, Yoggam1 commented on jni/java/wallet/core/java/TangemSigner.java
> +        byte[] data = input.toByteArray();
Исправил

2023-03-17 13:23 UTC, megakoko requested changes

2023-03-17 13:23 UTC, megakoko commented on android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/tron/TestTronTransactionSigner.kt
> +        val signer = PrivateKeySigner(PrivateKey(signingInput.privateKey.toByteArray()), TRON)
```suggestion
        // TANGEM
        val signer = PrivateKeySigner(PrivateKey(signingInput.privateKey.toByteArray()), TRON)
```

2023-03-17 13:23 UTC, megakoko commented on jni/cpp/AnySigner.cpp
> +    jclass signerClazz = env->GetObjectClass(signer);
signerClass

2023-03-17 13:23 UTC, megakoko commented on jni/cpp/AnySigner.cpp
> +    cachedJVM = nullptr;
Обнулять надо там, где получаем объект. То есть в Java_wallet_core_java_AnySigner_nativeSignExternally

2023-03-17 13:51 UTC, megakoko commented on jni/cpp/AnySigner.cpp
> +    jclass signerClazz = env->GetObjectClass(signer);
Окей

2023-03-17 14:05 UTC, megakoko approved these changes

2023-03-17 14:07 UTC, merged